version: "3"

services:
  php:
    #image: php:7.3-apache
    build: ./docker/php
    ports: 
      - 85:80
    container_name: "nosql_php"
    volumes:
      - ./docroot:/var/www/html:cached # User-guided caching

  memcached:
    container_name: "nosql_memcached"
    image: memcached

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080