version: "3"

services:
  php:
    #image: php:7.3-apache
    build: ./docker/php
    ports: 
      - 85:80
    container_name: "nosql_php"
    volumes:
      - ./docroot:/var/www/html:cached # User-guided caching

  # Memcache
  memcached:
    container_name: "nosql_memcached"
    image: memcached
  # Memcache | Admin tool
  phpmemcacheadmin:
    image: hitwe/phpmemcachedadmin
    ports:
     - "86:80"

  # Redis
  redis:
    image: redis
    container_name: "nosql_redis"
    hostname: redis
#    volumes:
#     - ./storage/redis/data:/data
#     ports:
#     - 6379:6379

  # Redis container with module RediSQL that support SQL queires
  redisql:
    image: siscia/redisql redis-cli
    container_name: 'nosq_redisql'
    hostname: 'nosq_redisql'

  # Redis | Admin Tool
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8087:8081"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8086:8080